/**
 * Core domain types for the interview flow.
 */

import type { Utterance } from "@/hooks/useUtteranceEvents";

/** Finite state machine states for the interview flow. */
export type InterviewPhase =
  | "WELCOME"
  | "LOBBY"
  | "INTRO"
  | "QUESTIONING"
  | "RESULTS";

/** An interview preset loaded from config/presets.config.json. */
export interface InterviewPreset {
  id: string;
  title: string;
  description: string;
  icon: string;
  persona_id?: string;
  replica_id?: string;
}

/** Tracks completion status of a single objective. */
export interface ObjectiveProgress {
  objective_name: string;
  label: string;
  completed: boolean;
  /**
   * Whether this objective actually fired during the call. Set true when
   * `conversation.objective.activated` (or `.completed`) arrives; stays
   * false for preloaded persona objectives the conversation never reached.
   */
  activated?: boolean;
  output_variables?: Record<string, string>;
  /** Wall-clock ms when `conversation.objective.activated` first fired. */
  activatedAt?: number;
  /** Wall-clock ms when `conversation.objective.completed` fired. */
  completedAt?: number;
}

/** A single perception observation from Raven end-of-call analysis. */
export interface PerceptionObservation {
  id: string;
  label: string;
  analysis: string;
}

/** Full interview result passed to ResultsScreen. */
export interface InterviewResult {
  objectives: ObjectiveProgress[];
  perceptionObservations: PerceptionObservation[];
  objectiveOutputs: Record<string, Record<string, string>>;
  /**
   * Captured user/replica utterances from the call. Empty when closed
   * captions were disabled or the call ended before any speech.
   */
  utterances: Utterance[];
}

/** A perception signal rendered as a labeled bar in the report. */
export interface PerceptionBar {
  label: string;
  /** Display value, e.g. "87%", "strong", "low". */
  value: string;
  /** 0–100 numeric value used for the bar fill width. */
  percent: number;
  /** When true, render the bar as a warning instead of the default fill. */
  warn?: boolean;
}

/** STAR-framework breakdown shown in the report. */
export interface StarBreakdown {
  situation: string;
  task: string;
  action: string;
  result: string;
}

/** A timestamped transcript moment flagged in the report. */
export interface TranscriptHighlight {
  timestamp: string;
  label: string;
  quote: string;
}

/** Numeric scores rendered at the top of the report. */
export interface InterviewScores {
  overall: number;
  technical: number;
  communication: number;
  starAdherence: number;
}

/**
 * Casting report data. Generated by the persona's `submit_audition_report`
 * post-call tool (Tavus' AI fills it from the transcript) and read back from
 * the conversation's `application.post_call_action_executed` event.
 */
export interface InterviewAnalysis {
  summary: string;
  scores?: InterviewScores;
  perceptionBars?: PerceptionBar[];
  starBreakdown?: StarBreakdown;
  transcriptHighlights?: TranscriptHighlight[];
}

/** A guardrail definition fetched from the Tavus API for a persona. */
export interface GuardrailDefinition {
  guardrail_name: string;
  guardrail_prompt: string;
  modality: string;
}

/** A single tool function exposed by the persona (LLM or perception). */
export interface PersonaTool {
  name: string;
  description?: string;
}

/** Active-layer info surfaced from the persona for the inspector "LAYERS" strip. */
export interface PersonaLayers {
  llm: { model: string | null };
  tts: { engine: string | null };
  perception: { model: string | null };
  conversational_flow: {
    turn_detection_model: string | null;
    turn_taking_patience: string | null;
    replica_interruptibility: string | null;
  };
}

/** Tools attached to the persona, split by layer. */
export interface PersonaTools {
  llmTools: PersonaTool[];
  visualTools: PersonaTool[];
  audioTools: PersonaTool[];
  perceptionModel: string | null;
  layers: PersonaLayers;
}

/** A guardrail displayed in the interview side panel. */
export interface GuardrailStatus {
  guardrail_name: string;
  label: string;
  description: string;
  modality: "verbal" | "visual";
  /** Whether this guardrail has been triggered/violated during the session. */
  triggered: boolean;
  /** Timestamp of most recent trigger, if any. */
  triggeredAt?: number;
  /** Number of times this guardrail has fired/violated this session. */
  violationCount: number;
  /** Wall-clock ms the guardrail was last evaluated (any related event). */
  lastEvaluatedAt?: number;
  /** Violation reason text from the most recent real guardrail event. */
  lastReason?: string;
}
